version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2023.1"
    volumes:
      - './homeassistant/config:/config'
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: false
    network_mode: host
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.01.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Detroit'
    env_file:
      - pihole.env
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale
    volumes:
      - './tailscale/var-lib:/var/lib'
      - './tailscale/dev-net-tun:/dev/net/tun'
    network_mode: host
    environment:
      - TS_NO_LOGS_NO_SUPPORT=true
      - TS_ACCEPT_DNS=false
    env_file:
      - tailscale.env
  npm:
    container_name: 'npm'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '8080:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt