version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - './mount/homeassistant/config:/config'
      - /etc/localtime:/etc/localtime:ro
    devices:
      # Passing through Zigbee receiver into Docker container
      - /dev/ttyACM0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: false
    network_mode: host
    env_file:
      - homeassistant.env
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    env_file:
      - syncthing.env
    volumes:
      - './mount/syncthing:/var/syncthing'
      - './mount:/var/optiplex'
#    ports:
#      - 8384:8384 # Web UI
#      - 22000:22000/tcp # TCP file transfers
#      - 22000:22000/udp # QUIC file transfers
#      - 21027:21027/udp # Receive local discovery broadcasts
    network_mode: host # use this instead of ports for easier local network discovery
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: 'America/Detroit'
      # When the job will run, 6 character cron.
      WATCHTOWER_SCHEDULE: "0 0 3 * * MON,WED,FRI"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      DOCKER_TLS_VERIFY: "true"
    env_file:
      - watchtower.env
