version: '3.8'

services:
  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - '../../mount/home-assistant/config:/config'
      - /etc/localtime:/etc/localtime:ro
    # user: "${PUID}:${PGID}"
    restart: unless-stopped
    privileged: true
    network_mode: host
